### ISSUE TITLE
Move to Docker

### ISSUE THREAD

**Issue by avaer** [webaverse/codespace#4]
It takes a bit of time to boot the codespace right now, a bit too long to be convenient.

I think that's mostly the `npm install` performing native builds for `mediasoup`.

We can probably optimize this by prepackaging the `node_modules` or other install material, other than the cert, into a Github Actions release which we download and unpack during install, rather than this slow build process.

**Comment by avaer** [comment]
The goals here are that:

1. bringing up the space is fast
2. the solution does not require constant manual intervention to keep up to date

**Comment by avaer** [comment]
We could also possibly leverage docker builds/images for this with Github Actions.

**Comment by avaer** [comment]
I experimented with the performance and it is still quite bad to start. I think we need to prebuild these images into Docker and pull them from there.

**Comment by avaer** [comment]
I'm going to try to wrangle with Github to find a way to get non-security destroying deploy keys for their container image hosting.

**Comment by avaer** [comment]
The github action should already have `GITHUB_TOKEN` for the repo owner if you are in the org/repo.

https://docs.github.com/en/actions/reference/authentication-in-a-workflow
https://github.com/webaverse/codespace/actions/runs/1154253910

**Comment by AGoblinKing** [comment]
I got the entire process of building a docker image with github actions, checking it into our ghcr repo, and using it as our .devcontainer on this branch https://github.com/webaverse/codespace/tree/feature-workflow-image.

This is still installing mediasoup and compiling the worker bin however.... I found this environment variable that'll win the day.

`process.env.MEDIASOUP_WORKER_BIN` sets the worker binary. Going to precompile the worker and set that. It'll skip building the worker (by far the longest part of the install) and use the binaries we pointed at. We can bind the version by vendorizing or having a github action on mediasoup version change check in an updated binary artifact of mediasoup-worker

Long term we could have an artifact depo but that seems like overkill for a mediasoup binary

**Comment by avaer** [comment]
Why is it still building again? There should be no need to install once using the right docker image.

**Comment by AGoblinKing** [comment]
the git clone seems to be destructive and blow away anything there previously. To resolve this I can stuff the files somewhere else or the above solution removes the need for a custom image entirely.

**Comment by AGoblinKing** [comment]
https://github.com/webaverse/codespace/tree/feature-mediasoup-worker here is a working proto of it. This codespace starts up dramatically faster.

**Comment by avaer** [comment]
This still seems still too slow of an install process. Basically can we get away without having `npm install` at all running on codespace startup?

https://github.com/webaverse/codespace/blob/fe829b295d2a5e098462400996110e008289df53/init.sh#L2

With docker, the goal would be to remove the `npm install` and `cp -R` or better yet `ln` the already installed `node_modules` into place.

**Comment by AGoblinKing** [comment]
Roger, I have been exploring other solutions between rebuilds but I should have the docker solution starting up quickly.

**Comment by AGoblinKing** [comment]
Avaer emailed https://docs.github.com/en/codespaces/customizing-your-codespace/prebuilding-codespaces-for-your-project which potentially solves this. I am still pushing on our own solution though.

**Comment by avaer** [comment]
Heads up that this is currently getting file `EACCESS` when starting the `codespace`. Either way I'm not blocked on it.

```2021-08-23T23:11:14.518Z mediasoup:ERROR:Worker worker process failed [pid:undefined]: spawn /workspaces/codespace/node_modules/dialog/mediasoup/worker/out/Release/mediasoup-worker EACCES
node_modules/debug/src/common.js:113
(node:26050) UnhandledPromiseRejectionWarning: Error: spawn /workspaces/codespace/node_modules/dialog/mediasoup/worker/out/Release/mediasoup-worker EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by AGoblinKing** [comment]
You should be able to rerun it again and it'll work. I'll write up that bug now. 

*https://github.com/webaverse/codespace/issues/8
